on: [push, pull_request]

name: AzureLogin_VM

jobs:
 build:
    runs-on: [windows-latest]
    steps:

    - name: Log in with Azure
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZ }}
      env:
       creds: ${{ secrets.VM }}
       admin-username: sai  
       admin-password: Miracle@123456
