on: [push, pull_request]

name: AzureLogin_VM

jobs:
 build:
    runs-on: [windows-latest]
    steps:

    - name: Log in with Azure
      uses: azure/login@v1
      with:
       creds: ${{ secrets.VM }}
 
